mips specific openssl build keeps failing, use generic linux

diff --git a/cross_build/Dockerfile.ingenic-mips b/cross_build/Dockerfile.ingenic-mips
--- a/cross_build/Dockerfile.ingenic-mips
+++ b/cross_build/Dockerfile.ingenic-mips
@@ -6,8 +6,10 @@ RUN tar xfj /opt/mips-gcc720-glibc229.tar.bz2 -C /opt/
 
 ENV CC=/opt/mips-linux-gnu-ingenic-gcc7.2.0-glibc2.29-fp64/bin/mips-linux-gnu-gcc
 ENV CXX=/opt/mips-linux-gnu-ingenic-gcc7.2.0-glibc2.29-fp64/bin/mips-linux-gnu-g++
-ENV CFLAGS="-mabi=32 -mips32 -Wa,--noexecstack"
-ARG OPENSSL_TARGET=linux-mips32
+ENV CFLAGS="-latomic"
+#ENV CFLAGS="-mabi=32 -mgp32"
+#ENV CFLAGS="-mabi=32 -mips32 -mgp32 -Wa,--noexecstack"
+ARG OPENSSL_TARGET=linux-generic64
 
 FROM base as mbedtls
 
@@ -17,8 +19,8 @@ WORKDIR /tmp/lib
 RUN curl -sSL https://github.com/Mbed-TLS/mbedtls/archive/refs/tags/v3.5.2.tar.gz | tar -xzf - --strip-components=1
 RUN ./scripts/config.py set MBEDTLS_SSL_DTLS_SRTP
 WORKDIR /tmp/build
-RUN cmake -DCMAKE_POSITION_INDEPENDENT_CODE=ON -DCMAKE_INSTALL_PREFIX=/tmp/install /tmp/lib
-RUN make -j 16 install
+RUN cmake -DCMAKE_C_FLAGS="${CFLAGS}" -DCMAKE_POSITION_INDEPENDENT_CODE=ON -DCMAKE_INSTALL_PREFIX=/tmp/install /tmp/lib
+RUN make -j 16 install || (echo "Make failed - dumping error logs and environment" >&2; env >&2; df -h >&2; cat CMakeFiles/CMakeError.log >&2; exit 1)
 
 FROM base as openssl
 
@@ -26,9 +28,8 @@ WORKDIR /tmp/lib
 RUN curl -sSL https://github.com/openssl/openssl/releases/download/openssl-3.2.1/openssl-3.2.1.tar.gz | tar -xzf - --strip-components=1
 WORKDIR /tmp/build
 RUN /tmp/lib/Configure --prefix=/tmp/install ${OPENSSL_TARGET}
-RUN make -j 16
-RUN make install_sw
-
+RUN make -j 16 
+RUN make -j 16 install_sw
 
 FROM base as libcurl
 
@@ -38,9 +39,8 @@ RUN curl -sSL https://github.com/curl/curl/archive/refs/tags/curl-8_6_0.tar.gz |
 COPY --from=openssl /tmp/install /tmp/dependencies
 
 WORKDIR /tmp/build
-RUN cmake -DCMAKE_POSITION_INDEPENDENT_CODE=ON -DCMAKE_INSTALL_PREFIX=/tmp/install -DOPENSSL_ROOT_DIR=/tmp/dependencies -DOPENSSL_INCLUDE_DIR=/tmp/dependencies/include /tmp/lib
+RUN cmake -DCMAKE_C_FLAGS="${CFLAGS}" -DCMAKE_POSITION_INDEPENDENT_CODE=ON -DCMAKE_INSTALL_PREFIX=/tmp/install -DOPENSSL_ROOT_DIR=/tmp/dependencies -DOPENSSL_INCLUDE_DIR=/tmp/dependencies/include /tmp/lib
 RUN make -j 16 install
-
 
 FROM base as example
 
@@ -58,7 +58,7 @@ COPY ./nabto-embedded-sdk /tmp/lib/nabto-embedded-sdk
 COPY ./.git /tmp/lib/.git
 
 WORKDIR /tmp/build
-RUN cmake -DCMAKE_BUILD_TYPE=Release -DNABTO_WEBRTC_BUILD_TESTS=OFF -DNABTO_WEBRTC_USE_VCPKG=OFF -DCMAKE_INSTALL_PREFIX=/tmp/install -DMbedTLS_ROOT=/tmp/dependencies -DCURL_ROOT=/tmp/dependencies -DOPENSSL_ROOT_DIR=/tmp/dependencies -DCMAKE_POLICY_DEFAULT_CMP0074=NEW -DCMAKE_POLICY_DEFAULT_CMP0135=NEW /tmp/lib
+RUN cmake -DCMAKE_C_FLAGS="${CFLAGS}" -DCMAKE_BUILD_TYPE=Release -DNABTO_WEBRTC_BUILD_TESTS=OFF -DNABTO_WEBRTC_USE_VCPKG=OFF -DCMAKE_INSTALL_PREFIX=/tmp/install -DMbedTLS_ROOT=/tmp/dependencies -DCURL_ROOT=/tmp/dependencies -DOPENSSL_ROOT_DIR=/tmp/dependencies -DCMAKE_POLICY_DEFAULT_CMP0074=NEW -DCMAKE_POLICY_DEFAULT_CMP0135=NEW /tmp/lib
 RUN make -j 16 install
 RUN file /tmp/install/bin/edge_device_webrtc
-#RUN $LDD /tmp/install/bin/edge_device_webrtc
+RUN $LDD /tmp/install/bin/edge_device_webrtc
